import React from 'react'
import { Header } from '../../Components/Header'
import TrolleyImg from '../../Assets/trolley Spares.png'
import Tubeimg from '../../Assets/TubelessTyre.png'
import CategoryCard from '../../Components/CategoryCard'
import Carousel from '../../Components/Carousel'
import Footer from '../../Components/Footer'